In [1]:
#-*-coding:utf-8-*- 

In [2]:
import pandas as pd 
import numpy as np

### * Feature Selection 

#### : Select features according to each selection standard methods 

#### ** 01. SelectKBest 

In [3]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2
X, y = load_digits(return_X_y=True)

In [9]:
print(f" * The shape of the array X : {X.shape}")
print(f" * The shape of the array y : {y.shape}")

 * The shape of the array X : (1797, 64)
 * The shape of the array y : (1797,)


In [11]:
# Init signature: SelectKBest(score_func=<function f_classif at 0x000002747397C160>, *, k=10)
# Docstring:     
# Select features according to the k highest scores.

# Parameters
# ----------
# score_func : callable
#     Function taking two arrays X and y, and returning a pair of arrays
#     (scores, pvalues) or a single array with scores.
#     Default is f_classif (see below "See also"). The default function only
#     works with classification tasks.

#     .. versionadded:: 0.18

# k : int or "all", optional, default=10
#     Number of top features to select.
#     The "all" option bypasses selection, for use in a parameter search.

# Attributes
# ----------
# scores_ : array-like of shape (n_features,)
#     Scores of features.

# pvalues_ : array-like of shape (n_features,)
#     p-values of feature scores, None if `score_func` returned only scores.

# Notes
# -----
# Ties between features with equal scores will be broken in an unspecified
# way.

# See also
# --------
# f_classif: ANOVA F-value between label/feature for classification tasks.
# mutual_info_classif: Mutual information for a discrete target.
# chi2: Chi-squared stats of non-negative features for classification tasks.
# f_regression: F-value between label/feature for regression tasks.
# mutual_info_regression: Mutual information for a continuous target.
# SelectPercentile: Select features based on percentile of the highest scores.
# SelectFpr: Select features based on a false positive rate test.
# SelectFdr: Select features based on an estimated false discovery rate.
# SelectFwe: Select features based on family-wise error rate.
# GenericUnivariateSelect: Univariate feature selector with configurable mode.

In [13]:
K_Selector = SelectKBest(score_func=chi2, k=20) 

In [15]:
X_new = K_Selector.fit_transform(X, y)

print(f" * The shape of New X-array : {X_new.shape}")

 * The shape of New X-array : (1797, 20)


In [18]:
K_Selector.scores_

array([          nan,  811.90700411, 3501.28249552,  698.9252572 ,
        438.52969882, 3879.81925999, 3969.45823205, 1193.5608181 ,
         24.79521396, 2953.83108764, 2583.65198939,  388.24205944,
        824.69094853, 3676.48924765, 1983.5796061 ,  597.24198237,
          8.95886124, 1924.21690377, 2409.27140681, 3556.31594594,
       4871.94194551, 4782.19921618, 2155.17378998,  376.76583333,
          7.90090158, 2471.82418401, 4515.48149826, 2986.64314847,
       3724.09567634, 3208.64686641, 5138.07412439,   35.71270718,
                 nan, 5688.25079535, 5262.46646904, 3165.0605867 ,
       3231.63943369, 2532.99695611, 3288.81403655,           nan,
        142.85082873, 3863.85787901, 6416.0867248 , 5448.25154235,
       4079.73153383, 2134.02540236, 4486.34097862,  313.53898127,
         70.39927392,  449.72327313, 2801.97224468, 1527.54519627,
       1653.15892311, 3073.99803898, 5251.21748723,  683.88227339,
          9.15254237,  851.06791492, 3800.2473108 ,  730.92975

In [32]:
K_Selector.pvalues_.round(4)

array([   nan, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.0032, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.4411, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.5442, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
          nan, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,    nan,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.4233, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ])

: Methods 

In [25]:
# 1. get_params 
# ----------------------
# * get_params([deep]): Get parameters for this estimator.
K_Selector.get_params() 

{'k': 20,
 'score_func': <function sklearn.feature_selection._univariate_selection.chi2(X, y)>}

In [26]:
# 2. get_support 
# ---------------------- 
# get_support([indices]): Get a mask, or integer index, of the features selected 
K_Selector.get_support() 

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False])

In [29]:
# 3. inverse_transform 
# ---------------------- 
# inverse_transform(X): Reverse the transformation operation 
X_returned = K_Selector.inverse_transform(X_new) 

print(X_returned.shape) 

(1797, 64)


In [ ]:
X_new = SelectKBest(chi2, k=20).fit_transform(X, y)
X_new.shape

In [47]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2
# X, y = load_digits(return_X_y=True)


# pd.DataFrame(load_digits(as_frame=True))
digits_data_ = load_digits(as_frame=True)

In [48]:
digits_data_.keys() 

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [ ]:
pd.DataFrame(digits_data_.data)

In [49]:
digits_data_.data

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [38]:
# * Func. for Selection of Best-K-Categorical features with signif. lv.(a=Type1Error) 
# ---------------------- 

import sklearn.feature_selection as fs 

def K_selector_with_a(df, colnames_X, colnames_y, score_func=fs.chi2, a=1e-3): 
    # from sklearn.feature_selection import chi2
    # from sklearn.feature_selection import SelectKBest
    
    K_selector = SelectKBest(score_func=score_func, k='all') 
    K_selector.fit_transform(df[colnames_X], df[colnames_y]) 

    return pd.Index(colnames_X)[K_selector.pvalues_ < a]

In [33]:
1e-3

0.001

In [35]:
from sklearn import feature_selection as fs

In [36]:
score_func = fs.f_classif

In [37]:
score_func

<function sklearn.feature_selection._univariate_selection.f_classif(X, y)>

In [ ]:
K_selector_with_a(df, colnames_X, colnames_y)